from winged_app.models import Container, Item

items = [
"Cracking The Coding Interview: Arrays and Strings",
"Cracking The Coding Interview: Linked Lists",
"Cracking The Coding Interview: Stacks and Queues",
"Cracking The Coding Interview: Trees and Graphs",
"Cracking The Coding Interview: Bit Manipulation",
"Cracking The Coding Interview: Brain Teasers",
"Cracking The Coding Interview: Object Oriented Design",
"Cracking The Coding Interview: Recursion",
"Cracking The Coding Interview: Sorting and Searching",
"Cracking The Coding Interview: Mathematical",
"Cracking The Coding Interview: Testing",
"Cracking The Coding Interview: System Design and Memory Limits",
"Cracking The Coding Interview: C++",
"Cracking The Coding Interview: Java",
"Cracking The Coding Interview: Databases",
"Cracking The Coding Interview: Low Level",
"Cracking The Coding Interview: Networking",
"Cracking The Coding Interview: Threads and Locks",
"Cracking The Coding Interview: Moderate",
"Cracking The Coding Interview: Hard",
"Cracking The Coding Interview: Solutions",
"Discrete Mathematics and It's Applications - The Foundations: Propositional Logic.",
"Discrete Mathematics and It's Applications - The Foundations: Applications of Propositional Logic.",
"Discrete Mathematics and It's Applications - The Foundations: Propositional Equivalences.",
"Discrete Mathematics and It's Applications - The Foundations: Predicates and Quantifiers.",
"Discrete Mathematics and It's Applications - The Foundations: Nested Quantifiers.",
"Discrete Mathematics and It's Applications - The Foundations: Rules of Inference.",
"Discrete Mathematics and It's Applications - The Foundations: Introduction to Proofs.",
"Discrete Mathematics and It's Applications - The Foundations: Proof Methods and Strategy.",
"Discrete Mathematics and It's Applications - Basic Structures: Sets.",
"Discrete Mathematics and It's Applications - Basic Structures: Set Operations.",
"Discrete Mathematics and It's Applications - Basic Structures: Functions.",
"Discrete Mathematics and It's Applications - Basic Structures: Sequences and Summations.",
"Discrete Mathematics and It's Applications - Basic Structures: Cardinality of Sets.",
"Discrete Mathematics and It's Applications - Basic Structures: Matrices.",
"Discrete Mathematics and It's Applications - Algorithms: Algorithms.",
"Discrete Mathematics and It's Applications - Algorithms: The Growth of Functions.",
"Discrete Mathematics and It's Applications - Algorithms: Complexity of Algorithms.",
"Discrete Mathematics and It's Applications - Number Theory and Cryptography: Divisibility and Modular Arithmetic.",
"Discrete Mathematics and It's Applications - Number Theory and Cryptography: Integer Representations and Algorithms.",
"Discrete Mathematics and It's Applications - Number Theory and Cryptography: Primes and Greatest Common Divisors.",
"Discrete Mathematics and It's Applications - Number Theory and Cryptography: Solving Congruences.",
"Discrete Mathematics and It's Applications - Number Theory and Cryptography: Applications of Congruences.",
"Discrete Mathematics and It's Applications - Number Theory and Cryptography: Cryptography.",
"Discrete Mathematics and It's Applications - Induction and Recursion: Mathematical Induction.",
"Discrete Mathematics and It's Applications - Induction and Recursion: Strong Induction and Well-Ordering.",
"Discrete Mathematics and It's Applications - Induction and Recursion: Recursive Definitions and Structural Induction.",
"Discrete Mathematics and It's Applications - Induction and Recursion: Recursive Algorithms.",
"Discrete Mathematics and It's Applications - Induction and Recursion: Program Correctness.",
"Discrete Mathematics and It's Applications - Counting: The Basics of Counting.",
"Discrete Mathematics and It's Applications - Counting: The Pigeonhole Principle.",
"Discrete Mathematics and It's Applications - Counting: Permutations and Combinations.",
"Discrete Mathematics and It's Applications - Counting: Binomial Coefficients and Identities.",
"Discrete Mathematics and It's Applications - Counting: Generalized Permutations and Combinations.",
"Discrete Mathematics and It's Applications - Counting: Generating Permutations and Combinations.",
"Discrete Mathematics and It's Applications - Discrete Probability: An Introduction to Discrete Probability.",
"Discrete Mathematics and It's Applications - Discrete Probability: Probability Theory.",
"Discrete Mathematics and It's Applications - Discrete Probability: Bayes’ Theorem.",
"Discrete Mathematics and It's Applications - Discrete Probability: Expected Value and Variance.",
"Discrete Mathematics and It's Applications - Advanced Counting Techniques: Applications of Recurrence Relations.",
"Discrete Mathematics and It's Applications - Advanced Counting Techniques: Solving Linear Recurrence Relations.",
"Discrete Mathematics and It's Applications - Advanced Counting Techniques: Divide-and-Conquer Algorithms and Recurrence Relations.",
"Discrete Mathematics and It's Applications - Advanced Counting Techniques: Generating Functions.",
"Discrete Mathematics and It's Applications - Advanced Counting Techniques: Inclusion–Exclusion.",
"Discrete Mathematics and It's Applications - Advanced Counting Techniques: Applications of Inclusion–Exclusion.",
"Discrete Mathematics and It's Applications - Relations: Relations and Their Properties.",
"Discrete Mathematics and It's Applications - Relations: n-ary Relations and Their Applications.",
"Discrete Mathematics and It's Applications - Relations: Representing Relations.",
"Discrete Mathematics and It's Applications - Relations: Closures of Relations.",
"Discrete Mathematics and It's Applications - Relations: Equivalence Relations.",
"Discrete Mathematics and It's Applications - Relations: Partial Orderings.",
"Discrete Mathematics and It's Applications - Graphs: Graphs and Graph Models.",
"Discrete Mathematics and It's Applications - Graphs: Graph Terminology and Special Types of Graphs.",
"Discrete Mathematics and It's Applications - Graphs: Representing Graphs and Graph Isomorphism.",
"Discrete Mathematics and It's Applications - Graphs: Connectivity.",
"Discrete Mathematics and It's Applications - Graphs: Euler and Hamilton Paths.",
"Discrete Mathematics and It's Applications - Graphs: Shortest-Path Problems.",
"Discrete Mathematics and It's Applications - Graphs: Planar Graphs.",
"Discrete Mathematics and It's Applications - Graphs: Graph Coloring.",
"Discrete Mathematics and It's Applications - Trees: Introduction to Trees.",
"Discrete Mathematics and It's Applications - Trees: Applications of Trees.",
"Discrete Mathematics and It's Applications - Trees: Tree Traversal.",
"Discrete Mathematics and It's Applications - Trees: Spanning Trees.",
"Discrete Mathematics and It's Applications - Trees: Minimum Spanning Trees.",
"Discrete Mathematics and It's Applications - Boolean Algebra: Boolean Functions.",
"Discrete Mathematics and It's Applications - Boolean Algebra: Representing Boolean Functions.",
"Discrete Mathematics and It's Applications - Boolean Algebra: Logic Gates.",
"Discrete Mathematics and It's Applications - Boolean Algebra: Minimization of Circuits.",
"Discrete Mathematics and It's Applications - Modeling Computation: Languages and Grammars.",
"Discrete Mathematics and It's Applications - Modeling Computation: Finite-State Machines with Output.",
"Discrete Mathematics and It's Applications - Modeling Computation: Finite-State Machines with No Output.",
"Discrete Mathematics and It's Applications - Modeling Computation: Language Recognition.",
"Discrete Mathematics and It's Applications - Modeling Computation: Turing Machines.",
]


def main(items):
    container = Container.objects.get(pk=165)

    for item in items:
        Item.objects.create(statement=item, parent_container=container, user=container.user)

def run():
    main(items)