version: 2.1

executors:
  python-postgres-executor:
    docker:
      - image: python:3.11.4
        environment:
          DJANGO_SETTINGS_MODULE: winged.settings
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pepito56
  node-executor:
    docker:
      - image: node:14

jobs:
  build_and_test_django:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Start PostgreSQL
          command: service postgresql start
      - run:
          name: Wait for PostgreSQL to start
          command: while ! nc -z localhost 5432; do sleep 1; done
      - run:
          name: Setup and Test Django
          command: |
            pip install -r requirements.txt
            cd django_winged
            python manage.py makemigrations
            python manage.py migrate
            python manage.py test

  build_and_test_vue:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Setup and Test Vue
          command: |
            cd vue_winged
            npm install
            npx jest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_django
      - build_and_test_vue
