version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.11.4
        environment:
          DJANGO_SETTINGS_MODULE: winged.settings
  node-executor:
    docker:
      - image: node:14

jobs:
  build_and_test_django:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Setup and Test Django
          command: |
            pip install -r requirements.txt
            cd django_winged
            python manage.py makemigrations
            python manage.py migrate
            python manage.py test

  build_and_test_vue:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Setup and Test Vue
          command: |
            cd vue_winged
            npm install
            npx jest
  deploy_to_local:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
          - "d4:41:ec:1b:5a:6d:23:49:e3:52:a8:fa:dd:28:19:89"
      - run:
          name: SSH and Update User Repo
          command: |
            ssh .flac@10.0.0.54 "cd C:/Users/.flac/Documents/GitHub/django_projects/winged_personal/winged && git pull pull C:/Users/.flac/Documents/GitHub/winged main"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_django
      - build_and_test_vue
