# Generated by Django 4.1.5 on 2023-01-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Spectrum',
        ),
        migrations.AddField(
            model_name='item',
            name='spectrums',
            field=models.ManyToManyField(blank=True, to='winged_app.spectrum'),
        ),
    ]
