# Generated by Django 4.1.6 on 2023-02-12 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winged_app', '0005_spectrumtype_spectrumvalue_remove_item_spectrums_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainerCategory',
            new_name='ContainerGroup',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='parent_category',
            new_name='parent_group',
        ),
        migrations.RenameField(
            model_name='containergroup',
            old_name='parent_category',
            new_name='parent_group',
        ),
    ]
