# Generated by Django 4.1.6 on 2023-02-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0007_remove_container_parent_group_container_is_collapsed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
