# Generated by Django 4.1.6 on 2023-02-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0008_item_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='spectrumvalue',
            unique_together={('spectrum_type', 'parent_item')},
        ),
    ]
