# Generated by Django 4.1.7 on 2023-03-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0010_alter_item_parent_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='parent_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.container'),
        ),
    ]
