# Generated by Django 4.1.7 on 2023-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0011_alter_container_parent_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrumtype',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
