# Generated by Django 4.1.7 on 2023-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0012_alter_spectrumtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumvalue',
            name='gpt_curated',
            field=models.BooleanField(default=False),
        ),
    ]
