# Generated by Django 4.2.3 on 2023-08-10 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0014_alter_container_last_opened_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='last_opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='statement_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
