# Generated by Django 4.2.3 on 2023-08-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0016_alter_container_last_opened_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
