# Generated by Django 4.2.3 on 2023-09-01 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winged_app', '0017_alter_container_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('statement_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaStatementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.criteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ai_model', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.systemprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='current_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.systempromptversion'),
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemVsTwoCriteriaAIComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(db_index=True, max_length=128)),
                ('criteria_choice', models.BooleanField(choices=[(True, 'Criteria 1'), (False, 'Criteria 2')], db_index=True, default=False)),
                ('response', models.TextField(default=None, null=True)),
                ('execution_in_seconds', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_1', to='winged_app.criteriastatementversion')),
                ('criteria_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_2', to='winged_app.criteriastatementversion')),
                ('item_compared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winged_app.item')),
                ('system_prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.systemprompt')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='current_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.criteriastatementversion'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
