# Generated by Django 4.2.3 on 2023-09-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0020_remove_criteriastatementversion_parent_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriastatementversion',
            name='parent_criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.criteria'),
        ),
        migrations.AddField(
            model_name='systempromptversion',
            name='parent_prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.systemprompt'),
        ),
    ]
