# Generated by Django 4.2.3 on 2023-09-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0022_rename_systempromptversion_systemprompttextversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='current_text',
            new_name='current_statement_version',
        ),
        migrations.RenameField(
            model_name='systemprompt',
            old_name='current_text',
            new_name='current_system_prompt_text',
        ),
    ]
