# Generated by Django 4.2.3 on 2023-09-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0023_rename_current_text_criteria_current_statement_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='current_statement_version',
            new_name='statement',
        ),
        migrations.RenameField(
            model_name='systemprompt',
            old_name='current_system_prompt_text',
            new_name='prompt_text',
        ),
    ]
