# Generated by Django 4.2.3 on 2023-09-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0024_rename_current_statement_version_criteria_statement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='statement',
            new_name='statement_version',
        ),
    ]
