# Generated by Django 4.2.3 on 2023-09-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0025_rename_statement_criteria_statement_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompt_text',
            new_name='prompt_text_version',
        ),
        migrations.RenameField(
            model_name='systemprompttextversion',
            old_name='prompt_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='itemvstwocriteriaaicomparison',
            name='system_prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.systemprompttextversion'),
        ),
    ]
