# Generated by Django 4.2.3 on 2023-09-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0026_rename_prompt_text_systemprompt_prompt_text_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='statement_version',
            new_name='criteria_statement_version',
        ),
    ]
