# Generated by Django 4.2.3 on 2023-09-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0027_rename_statement_version_criteria_criteria_statement_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriastatementversion',
            name='updated_at',
        ),
    ]
