# Generated by Django 4.2.3 on 2023-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0028_remove_criteriastatementversion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvstwocriteriaaicomparison',
            name='user_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemvstwocriteriaaicomparison',
            name='ai_model',
            field=models.CharField(db_index=True, default=None, max_length=128, null=True),
        ),
    ]
