# Generated by Django 4.2.5 on 2023-10-11 19:25

from django.conf import settings
from django.db import migrations, models, transaction
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winged_app', '0029_itemvstwocriteriaaicomparison_user_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel("StatementVersion", "ItemStatementVersion"),
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria_statement_version',
            new_name='current_criteria_statement_version',
        ),
        migrations.RenameField(
            model_name='itemvstwocriteriaaicomparison',
            old_name='criteria_1',
            new_name='criteria_statement_version_1',
        ),
        migrations.RenameField(
            model_name='itemvstwocriteriaaicomparison',
            old_name='criteria_2',
            new_name='criteria_statement_version_2',
        ),
        migrations.RenameField(
            model_name='itemvstwocriteriaaicomparison',
            old_name='system_prompt',
            new_name='system_prompt_text_version',
        ),
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompt_text_version',
            new_name='current_prompt_text_version',
        ),
        migrations.AddField(
            model_name='item',
            name='current_statement_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.itemstatementversion'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='statement',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='prompt_text_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='text',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='criteriastatementversion',
            name='statement',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='systemprompttextversion',
            name='text',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='itemstatementversion',
            name='statement',
            field=models.TextField(default=None, max_length=140, null=True),
        ),
    ]
