# Generated by Django 4.2.5 on 2023-10-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0030_itemstatementversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvstwocriteriaaicomparison',
            name='item_compared_statement_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.itemstatementversion'),
        ),
    ]
