# Generated by Django 4.2.5 on 2023-10-11 23:35

from django.db import migrations

def migrate_item_compared_to_item_statement_version(apps, schema_editor):
    ItemVsTwoCriteriaAIComparison = apps.get_model('winged_app', 'ItemVsTwoCriteriaAIComparison')

    for comparison in ItemVsTwoCriteriaAIComparison.objects.all():
        if comparison.item_compared is None or comparison.item_compared.current_statement_version is None:
            print(f"Debug Info: comparison.id={comparison.id}, item_compared={comparison.item_compared}, current_statement_version={getattr(comparison.item_compared, 'current_statement_version', 'N/A')}")
        else:
            comparison.item_compared_statement_version = comparison.item_compared.current_statement_version
            comparison.save()

class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0032_remove_itemvstwocriteriaaicomparison_item_compared'),
    ]

    operations = [
        migrations.RunPython(migrate_item_compared_to_item_statement_version),
    ]
