# Generated by Django 4.2.5 on 2023-10-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0036_alter_itemvstwocriteriaaicomparison_criteria_statement_version_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='is_on_done_tab',
            field=models.BooleanField(default=False),
        ),
    ]
