# Generated by Django 4.2.5 on 2023-11-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winged_app', '0037_container_is_on_done_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumDoublyLinkedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumDoublyLinkedListNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=19, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_node', to='winged_app.spectrumdoublylinkedlistnode')),
                ('parent_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.item')),
                ('parent_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.spectrumdoublylinkedlist')),
                ('prev', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_node', to='winged_app.spectrumdoublylinkedlistnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spectrumdoublylinkedlist',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='winged_app.spectrumdoublylinkedlistnode'),
        ),
        migrations.AddField(
            model_name='spectrumdoublylinkedlist',
            name='parent_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.container'),
        ),
        migrations.AddField(
            model_name='spectrumdoublylinkedlist',
            name='parent_criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='winged_app.criteria'),
        ),
        migrations.AddField(
            model_name='spectrumdoublylinkedlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
