# Generated by Django 4.2.5 on 2023-11-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0038_spectrumdoublylinkedlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumdoublylinkedlist',
            name='evaluative',
            field=models.BooleanField(choices=[(True, 'EVALUATIVE'), (False, 'COMPARATIVE')], default=False),
        ),
    ]
