# Generated by Django 4.2.5 on 2023-11-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0039_spectrumdoublylinkedlist_evaluative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrumdoublylinkedlistnode',
            name='data',
            field=models.DecimalField(decimal_places=19, max_digits=20, null=True),
        ),
    ]
