# Generated by Django 4.2.5 on 2023-11-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0040_alter_spectrumdoublylinkedlistnode_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrumdoublylinkedlist',
            name='parent_criteria',
        ),
        migrations.AddField(
            model_name='spectrumdoublylinkedlist',
            name='criterion_statement_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winged_app.criteriastatementversion'),
        ),
    ]
