# Generated by Django 4.2.5 on 2023-11-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winged_app', '0041_remove_spectrumdoublylinkedlist_parent_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrumdoublylinkedlistnode',
            name='next',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_node', to='winged_app.spectrumdoublylinkedlistnode'),
        ),
        migrations.AlterField(
            model_name='spectrumdoublylinkedlistnode',
            name='prev',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_node', to='winged_app.spectrumdoublylinkedlistnode'),
        ),
    ]
