# Generated by Django 4.2.5 on 2023-11-09 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winged_app', '0042_alter_spectrumdoublylinkedlistnode_next_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpectrumDoublyLinkedListNode',
            new_name='DoublyLinkedListNode',
        ),
        migrations.AlterField(
            model_name='spectrumdoublylinkedlist',
            name='evaluative',
            field=models.BooleanField(choices=[(True, 'EVALUATIVE'), (False, 'COMPARATIVE')], default=True),
        ),
    ]
