# Generated by Django 4.2.5 on 2023-11-11 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winged_app', '0043_rename_spectrumdoublylinkedlistnode_doublylinkedlistnode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criteria',
            new_name='Criterion',
        ),
        migrations.RenameModel(
            old_name='CriteriaStatementVersion',
            new_name='CriterionStatementVersion',
        ),
        migrations.RenameField(
            model_name='criterion',
            old_name='current_criteria_statement_version',
            new_name='current_criterion_statement_version',
        ),
        migrations.RenameField(
            model_name='criterionstatementversion',
            old_name='parent_criteria',
            new_name='parent_criterion',
        ),
        migrations.RemoveField(
            model_name='itemvstwocriteriaaicomparison',
            name='criteria_choice',
        ),
        migrations.RemoveField(
            model_name='itemvstwocriteriaaicomparison',
            name='criteria_statement_version_1',
        ),
        migrations.RemoveField(
            model_name='itemvstwocriteriaaicomparison',
            name='criteria_statement_version_2',
        ),
        migrations.AddField(
            model_name='itemvstwocriteriaaicomparison',
            name='criterion_choice',
            field=models.BooleanField(choices=[(True, 'Criterion 1'), (False, 'Criterion 2')], db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='itemvstwocriteriaaicomparison',
            name='criterion_statement_version_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_criterion_one_item_vs_two_criteria_comparisons', to='winged_app.criterionstatementversion'),
        ),
        migrations.AddField(
            model_name='itemvstwocriteriaaicomparison',
            name='criterion_statement_version_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_criterion_one_item_vs_two_criteria_comparisons', to='winged_app.criterionstatementversion'),
        ),
        migrations.AlterField(
            model_name='doublylinkedlistnode',
            name='data',
            field=models.DecimalField(decimal_places=19, default=None, max_digits=20, null=True),
        ),
    ]
